extends:
  # https://github.com/import-js/eslint-plugin-import#typescript
  - plugin:import/recommended
  - plugin:import/typescript
  # https://prettier.io/docs/en/related-projects.html#eslint-integrations
  # `eslint-config-prettier`, turns off all ESLint rules that are unnecessary or might conflict with Prettier

plugins: [import, oclif]
parserOptions:
  project: 
    "./tsconfig.json"
  sourceType:
    "module"
settings:
  import/parsers:
    # https://github.com/alexgorbatchev/eslint-import-resolver-typescript#configuration
    '@typescript-eslint/parser': [.ts, .tsx]
  import/resolver:
    typescript:
      # always try to resolve types under `<root>@types` directory even it doesn't contain any source code, like `@types/unist`
      alwaysTryTypes: true,

      # Choose from one of the "project" configs below or omit to use <root>/tsconfig.json by default
      # use <root>/path/to/folder/tsconfig.json
      project: './'

rules:
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  '@typescript-eslint/no-empty-interface':
    [0, { import/no-named-as-default-member: 0 }]
  # '@typescript-eslint/consistent-type-imports':
  #   [1, { disallowTypeAnnotations: false }]
  '@typescript-eslint/triple-slash-reference':
    [0, { no-unused-expressions: off }]
  '@typescript-eslint/array-type': 0
