-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."dataschemas" add column "branch" text
--  not null default 'main';
