-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."access_lists" add column "name" text
--  not null default 'Empty access list';
