-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."member_credentials" add column "datasource_id" uuid
--  not null;
