-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."credentials" add column "access_type" text
--  not null default 'shared';
