-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."datasources" add column "auth" text
--  not null default 'shared';
